### PR TITLE
Changed README.md text

### PR DESCRIPTION
**Pull request by nathzi1505**

### CODE REVIEW

**Comment by ivy-leaves** [comment]
Hey @nathzi1505, Thanks for your fantastic PR.
We would like invite to be a Collaborator on our Ivy Discord Server.
If you would love to accept our invite, feel free to say Hi! at https://discord.com/invite/sXyFF8tDtm and reply with your discord handle HERE as a comment.
Once done, one of the team members will be granting you a "Collaborator" role in our discord server.

**Comment by ivy-leaves** [comment]
Hey @nathzi1505, Thanks for your fantastic PR.
We would like invite to be a Collaborator on our Ivy Discord Server.
If you would love to accept our invite, feel free to say Hi! at https://discord.com/invite/sXyFF8tDtm and reply with your discord handle (eg. abcd#1234) HERE as a comment.
Once done, one of the team members will be granting you a "Collaborator" role in our discord server.

**Comment by nathzi1505** [comment]
Hi there! Thanks for the invite. Here is my discord handle p3jitnathuk#5640.

**Comment by ivy-leaves** [comment]
Thanks @nathzi1505, We have added you as a Contributor in our server ✌.

**Comment by ivy-leaves** [comment]
Thanks @nathzi1505, We have added you as a Contributor in our server ✌.

**Comment by ivy-leaves** [comment]
Thanks @nathzi1505, We have added you as a Contributor in our server ✌.

**Pull request merged**
